[unix_http_server]
file=/var/run/supervisor.sock  ; Изменили путь для простоты
chmod=0777

[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid  ; Упрощенный путь
user=root
umask=000  ; Максимально разрешающие права

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:queue]
command=php /var/www/html/artisan queue:work --tries=3 --timeout=300
user=www-data
environment=
  APP_ENV="%(ENV_APP_ENV)s",
  DB_CONNECTION="%(ENV_DB_CONNECTION)s"
stdout_logfile=/var/log/worker/queue.out.log
stderr_logfile=/var/log/worker/queue.err.log

[program:scheduler]
command=bash -c "while true; do php /var/www/html/artisan schedule:run --no-interaction; sleep 10; done"
# command=bash -c "while true; do flock -n /tmp/scheduler.lock php /var/www/html/artisan schedule:run --no-interaction; sleep 10; done"
user=www-data
environment=
    APP_ENV="%(ENV_APP_ENV)s",
    DB_CONNECTION="%(ENV_DB_CONNECTION)s"
stdout_logfile=/var/log/worker/scheduler.out.log
stderr_logfile=/var/log/worker/scheduler.err.log
autostart=true
autorestart=true

# Новый сервис для отправки логов
[program:log-sender]
command=/usr/local/bin/log-sender.sh
autostart=true
autorestart=false
startsecs=0
startretries=0
user=root
stdout_logfile=/var/log/worker/log-sender.out.log
stderr_logfile=/var/log/worker/log-sender.err.log

# TELEGRAM ЗАГОТОВКА
[program:telegram-updates]
command=php /var/www/html/artisan command:TGgetUpdates
autostart=true
autorestart=true
startretries=5           ; Количество попыток перезапуска
startsecs=1              ; Сколько секунд программа должна проработать, чтобы считаться успешно запущенной
stopwaitsecs=30          ; Время ожидания завершения программы
retrydelay=600           ; Интервал между попытками перезапуска (10 минут)
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/worker/telegram-updates.log

# VK ЗАГОТОВКА
[program:vk-updates]
command=php /var/www/html/artisan command:VKgetUpdates
autostart=true
autorestart=true
startretries=5           ; Количество попыток перезапуска
startsecs=1              ; Сколько секунд программа должна проработать, чтобы считаться успешно запущенной
stopwaitsecs=30          ; Время ожидания завершения программы
retrydelay=600           ; Интервал между попытками перезапуска (10 минут)
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/worker/vk-updates.log