FROM gitflic.myidon.site:80/debian:bookworm

# Установка OpenVPN и iproute2
RUN apt-get update && apt-get install -y openvpn iproute2 curl iputils-ping iptables \
&& rm -rf /var/lib/apt/lists/*

# Установка NVM и Node.js
ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=22.15.0
RUN mkdir -p "$NVM_DIR" \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Настройка PATH
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"