FROM gitflic.myidon.site:80/php:8.3-fpm
WORKDIR /var/www/html

# Устанавливаем PHP расширения, базовые утилиты и системные зависимости
RUN apt-get update && apt-get install -y \
    mariadb-client \
    net-tools \
    iputils-ping \
    curl \
    unzip \
    iptables \
    grep \
    procps \
    libssh2-1-dev \
    redis-tools \
    supervisor \
    && docker-php-ext-install pdo pcntl pdo_mysql \
    && pecl install ssh2-1.3.1 redis \
    && docker-php-ext-enable ssh2 \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer \
    --version=2.7.1

# Настройка Supervisor
RUN mkdir -p /var/run/supervisor && \
    chown www-data:www-data /var/run/supervisor && \
    chmod 770 /var/run/supervisor

# Настройка переменных окружения для Composer
ENV COMPOSER_HOME=/composer
ENV PATH=$PATH:/composer/vendor/bin

# Установка NVM и Node.js
ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=22.15.0
RUN mkdir -p "$NVM_DIR" \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Настройка PATH
ENV PATH="$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH"

# Установка Laravel и зависимостей
RUN composer create-project --prefer-dist laravel/laravel /var/www/html.dist \
    && composer require \
    --working-dir=/var/www/html.dist

# Указываем рабочую директорию
WORKDIR /var/www/html